local test = require("santoku.test")

local crypto = require("santoku.monocypher")

local arr = require("santoku.array")

local err = require("santoku.error")
local assert = err.assert

test("derive_identity", function ()
  local id = crypto.derive_identity("test-secret-passphrase-123")
  assert(id ~= nil)
  assert(type(id:sub()) == "string")
  assert(type(id:public_key()) == "string")
end)

test("derive_identity deterministic", function ()
  local id1 = crypto.derive_identity("test-secret")
  local id2 = crypto.derive_identity("test-secret")
  assert(id1:sub() == id2:sub())
  assert(id1:public_key() == id2:public_key())
end)

test("identity sign and export", function ()
  local id = crypto.derive_identity("test-secret")
  local sig = id:sign("hello world")
  assert(type(sig) == "string")
  assert(#sig > 0)
  local exported = id:export()
  assert(type(exported) == "table")
  assert(exported.sub ~= nil)
  assert(exported.signing_key ~= nil)
  assert(exported.public_key ~= nil)
end)

test("import_identity roundtrip", function ()
  local id1 = crypto.derive_identity("test-secret")
  local exported = id1:export()
  local id2 = crypto.import_identity(exported)
  assert(id1:sub() == id2:sub())
  assert(id1:public_key() == id2:public_key())
  assert(id1:sign("test") == id2:sign("test"))
end)

test("import_key roundtrip", function ()
  local id = crypto.derive_identity("test-secret")
  local key1 = crypto.derive_key("test-secret", id)
  local exported = key1:export()
  local key2 = crypto.import_key(exported)
  assert(key1:export() == key2:export())
end)

test("encrypt decrypt roundtrip", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local plaintext = "hello world"
  local ciphertext = key:encrypt(plaintext)
  assert(ciphertext ~= plaintext)
  local decrypted = key:decrypt(ciphertext)
  assert(decrypted == plaintext)
end)

test("encrypt decrypt empty string", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local plaintext = ""
  local ciphertext = key:encrypt(plaintext)
  local decrypted = key:decrypt(ciphertext)
  assert(decrypted == plaintext)
end)

test("encrypt decrypt with aad roundtrip", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local ciphertext = key:encrypt("hello", "sub:id-1")
  local decrypted = key:decrypt(ciphertext, "sub:id-1")
  assert(decrypted == "hello")
end)

test("decrypt wrong aad fails", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local ciphertext = key:encrypt("hello", "sub:id-1")
  local result, errmsg = key:decrypt(ciphertext, "sub:id-2")
  assert(result == nil)
  assert(errmsg == "decryption failed")
end)

test("decrypt aad-bound without aad fails", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local ciphertext = key:encrypt("hello", "sub:id-1")
  local result, errmsg = key:decrypt(ciphertext)
  assert(result == nil)
  assert(errmsg == "aad mismatch")
end)

test("decrypt unbound blob with aad fails", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local ciphertext = key:encrypt("hello")
  local result, errmsg = key:decrypt(ciphertext, "sub:id-1")
  assert(result == nil)
  assert(errmsg == "aad mismatch")
end)

test("decrypt wrong key fails", function ()
  local id1 = crypto.derive_identity("secret1")
  local key1 = crypto.derive_key("secret1", id1)
  local id2 = crypto.derive_identity("secret2")
  local key2 = crypto.derive_key("secret2", id2)
  local ciphertext = key1:encrypt("test")
  local result, errmsg = key2:decrypt(ciphertext)
  assert(result == nil)
  assert(errmsg == "decryption failed")
end)

test("sign_request and verify_request", function ()
  local id = crypto.derive_identity("test-secret")
  local body = "request body"
  local sig = id:sign_request(body)
  assert(type(sig) == "string")
  local ok, err = crypto.verify_request(id:public_key(), sig, id:sub(), body)
  assert(ok == true, err)
end)

test("verify_request wrong signature fails", function ()
  local id = crypto.derive_identity("test-secret")
  local body = "request body"
  local id2 = crypto.derive_identity("other-secret")
  local sig2 = id2:sign_request(body)
  local ok, errmsg = crypto.verify_request(id:public_key(), sig2, id:sub(), body)
  assert(ok == nil)
  assert(errmsg == "invalid_signature")
end)

test("generate passphrase", function ()
  local secret = crypto.generate()
  assert(type(secret) == "string")
  local words = {}
  for w in secret:gmatch("%S+") do
    words[#words + 1] = w
  end
  assert(#words == 6)
end)

test("validate passphrase", function ()
  local secret = crypto.generate()
  assert(crypto.validate(secret) == true)
end)

test("validate rejects 20-char path", function ()
  assert(crypto.validate("Sh0rt!Pass") == false)
  assert(crypto.validate("ThisIsALongPassword1!") == false)
end)

test("validate rejects short diceware", function ()
  assert(crypto.validate("abacus abdomen abdominal abide abiding ability") == true)
  assert(crypto.validate("abacus abdomen abdominal abide abiding") == false)
end)

test("validate invalid passphrase", function ()
  assert(crypto.validate("invalid-words-here-now-test-foo") == false)
end)

test("validate accepts hyphenated EFF entries", function ()
  assert(crypto.validate("abacus abdomen abdominal abide abiding ability felt-tip drop-down") == true)
  assert(crypto.validate("t-shirt yo-yo abacus abdomen abdominal abide abiding ability") == true)
end)

test("validate accepts every output of generate (1000 iter)", function ()
  for _ = 1, 1000 do
    local secret = crypto.generate()
    assert(crypto.validate(secret) == true, "generate produced invalid: " .. secret)
  end
end)

test("derive_identity custom argon2 params", function ()
  local id = crypto.derive_identity("test-secret", 1024, 1)
  local exported = id:export()
  assert(exported.argon2_memory == 1024)
  assert(exported.argon2_passes == 1)
end)

test("derive_identity default argon2 params", function ()
  local id = crypto.derive_identity("test-secret")
  local exported = id:export()
  assert(exported.argon2_memory == 65536)
  assert(exported.argon2_passes == 3)
end)

test("import_identity preserves argon2 params", function ()
  local id1 = crypto.derive_identity("test-secret", 2048, 2)
  local id2 = crypto.import_identity(id1:export())
  local exported = id2:export()
  assert(exported.argon2_memory == 2048)
  assert(exported.argon2_passes == 2)
end)

test("import_identity defaults missing argon2 params", function ()
  local id1 = crypto.derive_identity("test-secret")
  local exported = id1:export()
  exported.argon2_memory = nil
  exported.argon2_passes = nil
  local id2 = crypto.import_identity(exported)
  local re_exported = id2:export()
  assert(re_exported.argon2_memory == 65536)
  assert(re_exported.argon2_passes == 3)
end)

test("derive_key reads params from identity", function ()
  local id = crypto.derive_identity("test-secret", 1024, 1)
  local key1 = crypto.derive_key("test-secret", id)
  local id_imported = crypto.import_identity(id:export())
  local key2 = crypto.derive_key("test-secret", id_imported)
  assert(key1:export() == key2:export())
end)

test("wrap_key unwrap_key roundtrip", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local wrap = string.rep(string.char(0x42), 32)
  local wrapped = crypto.wrap_key(key, wrap)
  assert(type(wrapped) == "string")
  local unwrapped = crypto.unwrap_key(wrapped, wrap)
  assert(unwrapped ~= nil)
  assert(unwrapped:export() == key:export())
end)

test("unwrap_key with wrong wrap fails", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local wrap1 = string.rep(string.char(0x42), 32)
  local wrap2 = string.rep(string.char(0x43), 32)
  local wrapped = crypto.wrap_key(key, wrap1)
  local result, errmsg = crypto.unwrap_key(wrapped, wrap2)
  assert(result == nil)
  assert(errmsg == "decryption failed")
end)

test("wrap_key rejects wrong wrap size", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local result, errmsg = crypto.wrap_key(key, "tooshort")
  assert(result == nil)
  assert(errmsg == "wrap_bytes must be exactly 32 bytes")
end)

test("hmac_sha256 deterministic hex", function ()
  local h1 = crypto.hmac_sha256("k", "message")
  local h2 = crypto.hmac_sha256("k", "message")
  assert(type(h1) == "string")
  assert(#h1 == 64)
  assert(h1 == h2)
  assert(crypto.hmac_sha256("k2", "message") ~= h1)
end)

test("hmac_sha1 rfc 2202 vectors", function ()
  local function bytes (...)
    return string.char(...)
  end
  assert(crypto.hmac_sha1(string.rep(bytes(0x0b), 20), "Hi There")
    == "b617318655057264e28bc0b6fb378c8ef146be00")
  assert(crypto.hmac_sha1("Jefe", "what do ya want for nothing?")
    == "effcdf6ae5eb2fa2d27416d5f184df9c259a7c79")
  assert(crypto.hmac_sha1(string.rep(bytes(0xaa), 20), string.rep(bytes(0xdd), 50))
    == "125d7342b9ac11cd91a39af48aa17b4f63f175d3")
  local key4 = {}
  for i = 1, 25 do key4[i] = i end
  assert(crypto.hmac_sha1(bytes(arr.spread(key4)), string.rep(bytes(0xcd), 50))
    == "4c9007f4026250c6bc8414f9bf50c86c2d7235da")
  assert(crypto.hmac_sha1(string.rep(bytes(0x0c), 20), "Test With Truncation")
    == "4c1a03424b55e07fe7f27be1d58bb9324a9a5a04")
  assert(crypto.hmac_sha1(string.rep(bytes(0xaa), 80),
    "Test Using Larger Than Block-Size Key - Hash Key First")
    == "aa4ae5e15272d00e95705637ce8a3b55ed402112")
  assert(crypto.hmac_sha1(string.rep(bytes(0xaa), 80),
    "Test Using Larger Than Block-Size Key and Larger Than One Block-Size Data")
    == "e8e99d0f45237d786d6bbaa7965c7808bbff1a91")
end)

test("key hmac deterministic hex", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local h = key:hmac("message")
  assert(type(h) == "string")
  assert(#h == 64)
  assert(key:hmac("message") == h)
end)

test("key bytes returns raw 32-byte material", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local raw = key:bytes()
  assert(type(raw) == "string")
  assert(#raw == 32)

  assert(key:bytes() == raw)
  assert(raw ~= key:export())

  assert(crypto.import_key(key:export()):bytes() == raw)
end)

test("key derive produces domain-separated subkeys", function ()
  local id = crypto.derive_identity("test-secret")
  local key = crypto.derive_key("test-secret", id)
  local a = key:derive("db")
  local b = key:derive("db")
  local c = key:derive("search")
  assert(#a:bytes() == 32)

  assert(a:bytes() == b:bytes())

  assert(a:bytes() ~= c:bytes())

  assert(a:bytes() ~= key:bytes())

  local ct = a:encrypt("hello")
  assert(a:decrypt(ct) == "hello")
  assert(c:decrypt(ct) == nil)
end)
